# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to run tests
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  run-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Run Tests"
          command: "echo 'Tests are running...'" # Simple command to print a message

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - run-tests: # Only the test job remains in the workflow
          filters:
            branches:
              only:
                - main
                - test # Run on commits to the main branch
